authenticationFailureReport OPERATION  ::=  {
	ARGUMENT AuthenticationFailureReportArg
	RESULT AuthenticationFailureReportRes
	ERRORS {
		systemFailure | 
		unexpectedDataValue | 
		unknownSubscriber
	}
	CODE local:15
}


