activateSS OPERATION ::= {
ARGUMENT Ss-ForBS 
RESULT Ss-Info 
ERRORS {
   systemFailure |
   dataMissing |
   unexpectedDataValue |
   bearerServiceNotProvisioned |
   teleserviceNotProvisioned |
   callBarred |
   illegalSS-Operation | 
   ss-ErrorStatus |
   ss-SubscriptionViolation |
   ss-Incompatibility |
   negativePW-Check |
   numberOfPW-AttemptsViolation}
CODE local:12
}

