provideSIWFSNumber OPERATION ::= { 
ARGUMENT ProvideSIWFSNumberArg 
RESULT ProvideSIWFSNumberRes
ERRORS {
   resourceLimitation |
   dataMissing |
   unexpectedDataValue |
   systemFailure}
CODE local:31
}

