registerPassword OPERATION ::= {
ARGUMENT SS-Code
RESULT NewPassword
ERRORS {
   systemFailure |
   dataMissing |
   unexpectedDataValue |
   callBarred |
   ss-SubscriptionViolation |
   pw-RegistrationFailure |
   negativePW-Check |
   numberOfPW-AttemptsViolation}
LINKED {
   getPassword}
CODE local:17
}

