NoteMM-EventArg :== SEQUENCE {
    serviceKey      ServiceKey,
    eventMet        [0] MM-Code
    imsi            [1] IMSI,
    msisdn          [2] ISDN-AddressString,
    locationInformation [3] LocationInformation OPTIONAL,
    supportedCAMELPhases    [5] SupportedCamelPhases OPTIONAL,
    extensionContainer       [6] ExtensionContainer  OPTIONAL,
    ...,
    locationInformationGPRS [7] LocationInformationGPRS OPTIONAL,
    offeredCamel4Funcationalities [8]   OfferedCamel4Functionalities OPTIONAL,
}
