UnknownSubscriberParam ::= SEQUENCE {
   extensionContainer ExtensionContainer OPTIONAL,
   ... ,
   unknownSubscriberDiagnostic UnknownSubscriberDiagnostic OPTIONAL}                                 


